changelog:
  categories:
    - title: ✨ Nouveautés
      labels:
        - PR-Feature
    - title: 🙌 Améliorations
      labels:
        - PR-Change
    - title: 🐛 Corrections de bugs
      labels:
        - PR-Bugfix
    - title: ⚠️ Modifications de l'API
      labels:
        - PR-Api
    - title: 🗣 Textes & Traductions
      labels:
        - PR-i18n
    - title: 🧱 Build
      labels:
        - PR-Build
    - title: 📄 Documentation
      labels:
        - PR-Doc
    - title: 🚧 En cours de développement 🚧
      labels:
        - PR-Wip
    - title: ⬆️ Mise à jour des dépendances
      labels:
        - PR-Dependencies

    - title: Autres
      labels:
        - PR-misc
        - "*"
